### ISSUE TITLE
Dragging ellipse width to 0 crashes Flare

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#10]
This happens in both Setup and Animate mode
![screen recording 2018-10-23 at 09 15 pm](https://user-images.githubusercontent.com/1817068/47405949-229a1180-d709-11e8-81c6-569b46c700eb.gif)

Here's the console:
![screen shot 2018-10-23 at 9 20 09 pm](https://user-images.githubusercontent.com/1817068/47406053-77d62300-d709-11e8-88df-bdfc4d9d16d0.png)

**Comment by luigi-rosso** [comment]
This should be fixed. Do we want to add a tentative label here too?

**Comment by neurowave** [comment]
Confirmed fixed and live on gotham. Sure for the tentative label.
