### ISSUE TITLE
File history and revisions not updating on public page

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#107]
The timeline part of public file preview page doesn't seem to be updating to show new revisions or any changes to the files.

**Comment by umberto-sonnino** [comment]
I think [I fixed it](https://github.com/2d-inc/2dimensions/commit/c2f085d4e09f978b1dbf96af0e912416fed60230), forgot to tag the issue! 
I also see all the updates for [your file](http://localhost:3000/a/pollux/files/flare/space/preview)!
