### ISSUE TITLE
Converting rounded rectangle to path still temporarily shows Corner Radius on the shape

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#108]
- Draw a rounded rectangle
- Press Convert to Path, or hit Enter with the rounded rectangle selected
- Corner Radius option remains in the Selection Panel.
- Change Corner Radius
- Flare crashes

If you deselect and reselect the shape, the Corner Radius is gone. But it's momentarily still there, which allows you to crash Flare by trying to change it.

Fix: Remove Corner Radius on the shape as soon as the user presses Convert to Path.

**Comment by luigi-rosso** [comment]
Forgot to mark this tentative, it should be fixed now.

**Comment by neurowave** [comment]
I can still repro this @luigi-rosso 

![screen recording 2018-12-09 at 04 52 pm](https://user-images.githubusercontent.com/1817068/49703442-23143c00-fbd3-11e8-9e59-e329d3fb7db1.gif)

**Comment by neurowave** [comment]
Fixed, thanks!! Closing!
