### ISSUE TITLE
Dragging a shape's width/height in Animate mode doesn't update input field

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#11]
![screen recording 2018-10-23 at 09 26 pm](https://user-images.githubusercontent.com/1817068/47406282-59245c00-d70a-11e8-8f6f-f4a53e01c2c9.gif)

**Comment by luigi-rosso** [comment]
Forgot to log this one as fixed, but this issue should be addressed now too.

**Comment by neurowave** [comment]
Works!
