### ISSUE TITLE
Flare runtimes need to be added to the runtimes page

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#118]
We need to add these to the runtimes page
![image 2018-11-23 at 8 24 21 am](https://user-images.githubusercontent.com/1817068/48953091-875bae00-eef9-11e8-8a8e-c14aa0e68c5c.png)

**Comment by neurowave** [comment]
Forgot to reference the commit, but I just fixed the styling of this and got it working for mobile devices. I think it's ready to go!

**Comment by mspanish** [comment]
The JS runtime is a dead link - did you pull this repo?  Flare is fast and looks very useful, I look forward to testing it out.

**Comment by luigi-rosso** [comment]
Sorry about that, we still have it marked private. We’ll clean up the readme and open it up by the end of the week.  Thanks for looking into Flare!
