### ISSUE TITLE
Switching revision on public page doesn't work

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#145]
This doesn't seem to work anymore. No errors in console.

<img width="1424" alt="image 2018-12-01 at 2 28 55 pm" src="https://user-images.githubusercontent.com/1817068/49329365-971c6780-f575-11e8-93dd-bbeec6d92c67.png">

**Comment by luigi-rosso** [comment]
These were actually forked events that were mis-represented as updates.

<img width="994" alt="screen shot 2018-12-02 at 1 46 19 pm" src="https://user-images.githubusercontent.com/454182/49340513-b92aee00-f638-11e8-9a4a-609390b58cce.png">

**Comment by neurowave** [comment]
This is fixed, thanks!
