### ISSUE TITLE
Something went wrong in the ui of Flare

### ISSUE THREAD

**Issue by uggyk** [2d-inc/support#148]
After going through Flare for a few days, I was able to put up some work on the animation. 

suddenly, out of nowhere. The UI stops working. This is what happens when I refresh:

![flare-issue](https://user-images.githubusercontent.com/45707311/49683071-60e06a00-fad8-11e8-84ee-eab5c14ed0ca.png)

- I duplicated the flare file, same thing happens once I click on "Animate". 
- I exported the flare file and dragged it into a new file, same thing happens when I click on "Animate".

I am out of options. the file is located here: https://www.2dimensions.com/a/uggy/files/Flare/new-file-4

**Comment by umberto-sonnino** [comment]
Should be working now!
