### ISSUE TITLE
Public preview page showing wrong revision?

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#157]
Not sure about this one, but check out the Space Demo page:
https://www.2dimensions.com/a/pollux/files/flare/space-demo/preview

It's showing the old moon animation. If you open the Flare file, it actually shows the new moon animation.

**Comment by neurowave** [comment]
I think there's something going on with our preview pages. I thought these were all separate bugs, but starting to notice too many… @luigi-rosso 

This file is also not showing any animations, though it does have an animation in Flare:
https://www.2dimensions.com/a/tarek360/files/flare/boring-star/preview

This file shows an animation, but nothing actually plays… in Flare it's fine:
https://www.2dimensions.com/a/nastya/files/flare/under-construction/preview

This file is pretty messed up on the preview page, but also looks fine in Flare:
https://www.2dimensions.com/a/JuanCarlos/files/flare/new-file-8/preview

This Nima file isn't showing up at all on the preview page:
https://www.2dimensions.com/a/pollux/files/nima/green-jelly/preview

This one also doesn't animate on the preview page, but works in Flare:
https://www.2dimensions.com/a/HamidrezaFarzi/files/flare/new-file/preview

**Comment by neurowave** [comment]
Looks like we're also not showing all the animations that are available… check this:
https://www.2dimensions.com/a/JuanCarlos/files/flare/penguin/preview

**Comment by luigi-rosso** [comment]
This was due to the preview cache not getting properly invalidated. These files should now show the correct revisions on the preview page.
