### ISSUE TITLE
Empty Screenshots

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#16]
"Meteor" and "Pizza Slice" used to have thumbnails. Now they're gone.
<img width="869" alt="image 2018-10-24 at 12 52 23 pm" src="https://user-images.githubusercontent.com/1817068/47457353-b3b1cc80-d78b-11e8-96f3-4eec2af260bc.png">

**Comment by SirStancelot** [comment]
Same on preview page of a project without a thumb, but in the "My Files" modal it is the other way around :)
<img width="1434" alt="screen shot 2018-10-27 at 12 43 25 am" src="https://user-images.githubusercontent.com/44517873/47600115-dc031c00-d981-11e8-94e9-f4cdf0c302d7.png">
<img width="1074" alt="screen shot 2018-10-27 at 12 43 43 am" src="https://user-images.githubusercontent.com/44517873/47600117-dd344900-d981-11e8-8683-846558bdaac4.png">
<img width="1429" alt="screen shot 2018-10-27 at 12 44 09 am" src="https://user-images.githubusercontent.com/44517873/47600118-dd344900-d981-11e8-90f0-366ef8e704fd.png">

**Comment by neurowave** [comment]
I think @luigi-rosso's latest builds have fixed this. Going to close.
