### ISSUE TITLE
Hierarchy doesn't go to full height when switching from Animate to Setup

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#164]
![screen recording 2018-12-14 at 09 14 am](https://user-images.githubusercontent.com/1817068/50017374-b73e2480-ff80-11e8-8655-2544ce70a2c7.gif)

**Comment by umberto-sonnino** [comment]
Should be working right with https://github.com/2d-inc/2dimensions/commit/e0ff7d31ffdf967bc5feff1a433a202cb2f490bd
