### ISSUE TITLE
SVG Importing Issues on Windows 10

### ISSUE THREAD

**Issue by rhelenagh** [2d-inc/support#166]
Hello,

In Flare I try to import an SVG file (created with Inkscape 0.92.3) with a drag and drop. Unfortunately only the message appears that the file is being imported and could take a couple of minutes. It is a file of 28.0KB use Windows 10.

Maybe you have some advice for me, thank you very much for your time and information and above all for creating Flare.

![image](https://user-images.githubusercontent.com/7809022/50018132-8a186300-ffce-11e8-9087-b1403f4d3dc0.png)

[rocket_export.zip](https://github.com/2d-inc/support/files/2681133/rocket_export.zip)

**Comment by luigi-rosso** [comment]
Thanks for reporting this, we have a fix. It will be up in the next few minutes. It will be build 1973 and above.

**Comment by rhelenagh** [comment]
@luigi-rosso Thanks Luigi, now the import works perfectly. 
Thanks for your time and effort.
