### ISSUE TITLE
Scrubbing animation in second artboard doesn't work

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#169]
Check out this file: https://www.2dimensions.com/a/maboox/files/flare/smyle-ui

You can scrub in the first artboard and watch the animation updated. But in the second artboard (called Page 1), when you scrub nothing happens. Playback works fine.

**Comment by contrite** [comment]
I had the same issue https://www.2dimensions.com/a/ndrsn/files/flare/new-file

**Comment by neurowave** [comment]
This looks fixed! Give it a shot @contrite! Feel free to re-open if you still run into a problem.
