### ISSUE TITLE
I can't see the last layer in the Dra

### ISSUE THREAD

**Issue by JcToon** [2d-inc/support#174]
I have a problem with the layers in the Drw Order. I can't see the last layer. Just the previous one is the body of the toast and the last one is the brightness of the toaster. I want to put the brightness of the toaster in front of the toast, but I can not access it.
![layer_1](https://user-images.githubusercontent.com/45951634/50181785-9d4c6b00-030d-11e9-976f-7fe130431e38.jpg)
![layer_2](https://user-images.githubusercontent.com/45951634/50181803-a89f9680-030d-11e9-9ba3-864a7d44fc19.jpg)

**Comment by neurowave** [comment]
Thanks for catching this! I just fixed it, should be live now.

The toast looks great, btw. 😃

**Comment by JcToon** [comment]
Now it is perfect. Thanks!!
