### ISSUE TITLE
Some files don't play on the public preview page

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#175]
They don't play even though they do have animations in Flare. Check out this example"
https://www.2dimensions.com/a/francesco/files/flare/dancing-man/preview

Doesn't play or show playback controls on preview page:
![image 2018-12-18 at 3 21 27 pm](https://user-images.githubusercontent.com/1817068/50189067-b1c24080-02d8-11e9-89d1-afa0838c37d1.png)

Has animation in Flare:
![image 2018-12-18 at 3 21 35 pm](https://user-images.githubusercontent.com/1817068/50189075-b71f8b00-02d8-11e9-9ba8-10085357ee28.png)

**Comment by neurowave** [comment]
Not sure if this is related or not, but this file doesn't even load in the public preview (but looks fine in Flare): https://www.2dimensions.com/a/stacey/files/flare/monster1/preview

**Comment by neurowave** [comment]
Here's another that doesn't load: https://www.2dimensions.com/a/JuanCarlos/files/nima/homo_erectus-1/preview

**Comment by Magistern** [comment]
same here: [https://www.2dimensions.com/a/kojo/files/nima/box-arm/preview ](https://www.2dimensions.com/a/kojo/files/nima/box-arm/preview )
actually, none of my animations preview.

**Comment by neurowave** [comment]
@Magistern the file you're linking to doesn't have any assets, that's why it doesn't show on the preview page. We don't currently have an option to show bones on the preview page (though we want to add it).

That said, two of your other files should be showing something because they do have assets… and they are both blank on the preview page. @luigi-rosso see links below

https://www.2dimensions.com/a/kojo/files/flare/pinch-shape/preview
https://www.2dimensions.com/a/kojo/files/nima/new-file-2/preview

**Comment by Magistern** [comment]
other than that, awesome tool! 
Any chance there will be other types of file exports in the future? (gif, m4v, etc)

**Comment by neurowave** [comment]
Thanks! Nima already has gif exporting! We definitely want to add more, and add them to Flare. You can provide feedback on upcoming features here: https://portal.productboard.com/twodimensions/tabs/1-under-consideration
