### ISSUE TITLE
Constraints switch to Strength 1 on Setup page on startup

### ISSUE THREAD

**Issue by MangoQuaffer** [2d-inc/support#189]
Currently when you have constraints, on the Setup section, the constraints' strength are all set to 1 on startup page even if you had previously set it to 0 last time you saved/had the file open.  All strength keys on animations are saved as expected.

This is counter-intuitive since everything else saves on the setup page exactly how you left it.  This can even make having a really complicated rig that needs a lot of fine tuning unbearable to work with if the default should be constraints strength should be 0.

**Comment by neurowave** [comment]
I can't seem to be able to reproduce this one. 

Here's what I did to test:
- added a distance constraint
- changed strength to 0 (in setup mode)
- refreshed the page
- constraint is correctly set to 0 (in setup mode).

Can you confirm that this is still happening? Which constraint specifically are you using?

**Comment by MangoQuaffer** [comment]
I used a transform constraint specifically, but I tested myself with a distance constraint and got same results.

Video showing problem in Nima:
https://www.dropbox.com/s/jg4g46ypggrfend/NimaConstraintBug.mov?dl=0

I'm using Chrome and PC just fyi.

I sent you my Nima file in the last e-mail I sent you.

This issue may or may not be related:
https://github.com/2d-inc/support/issues/193

**Comment by luigi-rosso** [comment]
I think I see why this is happening. We'll have a fix soon!

**Comment by MangoQuaffer** [comment]
Thanks!!! No rush, but very important bug :) lol I was scared at first that I messed up my character some how. Getting more free time soon to work on game.

**Comment by MangoQuaffer** [comment]
oh was referring to the draw order one, but just let me know if i have to rebuild some parts of character for some reason haha (no reply needed)

**Comment by MangoQuaffer** [comment]
Unless you're tackling any trailing bugs related to this, looks like its solved at least for Nima for sure! Constraints stay where you left them in set up mode now. Thanks!!

**Comment by luigi-rosso** [comment]
Great!
