### ISSUE TITLE
Creating a new path under a shape layer is offset

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#200]
Creating a new path under a shape layer (using a shape tool) seems to be offset (maybe by the artboard dimensions?). See gif:

![2019-01-05 13 23 22](https://user-images.githubusercontent.com/1817068/50729384-7c498f80-10ed-11e9-82f4-ed9938deff0f.gif)

This also seems to reset the shape's fill. Turning fill on/off fixes it:
![2019-01-05 13 25 08](https://user-images.githubusercontent.com/1817068/50729387-91262300-10ed-11e9-9fa3-f2856c76f208.gif)

**Comment by luigi-rosso** [comment]
This should be fixed!
