### ISSUE TITLE
Problem with clipping.

### ISSUE THREAD

**Issue by JcToon** [2d-inc/support#206]
A problem has appeared that I think was solved. When you clipping with a shape, if you want to stop doing it, and you eliminate the clipping option, the shape disappears. The form is, but it is not visible.
[20190111_173716.zip](https://github.com/2d-inc/support/files/2750466/20190111_173716.zip)

**Comment by luigi-rosso** [comment]
Nice catch, thank you! Fix is incoming. Your new recorder is working very well!

**Comment by JcToon** [comment]
Yeeessss!!
