### ISSUE TITLE
Is it possible to translate a node on a path 

### ISSUE THREAD

**Issue by SaeedMasoumi** [2d-inc/support#223]
Here is my [sample](https://www.2dimensions.com/a/SaeedMasoumi/files/flare/rekab/preview), I want to translate my blue node on a path which created with the pen tool. 

I know it's possible with defining multiple translate animations but Im trying to find an easy alternative.

**Comment by neurowave** [comment]
Hi @SaeedMasoumi, this is something we've talked about but we don't currently support it. Please submit a request on our roadmap! https://portal.productboard.com/twodimensions
