### ISSUE TITLE
Export Flare animation

### ISSUE THREAD

**Issue by waltermaldonado** [2d-inc/support#224]
I got to know Flare yesterday and got impressed with its capabilities. However I cannot find any way to export flare animations to common extensions like .gif (available in Nima) or .svg. Am I missing something or it is really impossible?

**Comment by neurowave** [comment]
Hi @waltermaldonado, this is on our roadmap, which you can vote on here: https://portal.productboard.com/twodimensions

We are currently focusing on features for real-time playback and interactivity, though we know this is high on the request list for a lot of users.

**Comment by johnknoop** [comment]
This is a must-have for me as well. I saw that there is a feature request on your roadmap about exporting _static_ SVG's. That won't add any value to me what so ever. What I would need is a way to export animated svg's for use on the web.

**Comment by avvari-da** [comment]
Any update on this?

**Comment by hasanaydins** [comment]
when is it coming ??

**Comment by nmay231** [comment]
The link above is broken, here's the new one https://portal.productboard.com/rive

**Comment by IsaaacD** [comment]
I've put together a tool that allows you to export keyframes in a zip from an export from rive.app. It's located at https://flare-sprite.herokuapp.com/ right now and uses the flare-js example as a jump off point.

You can drag and drop .flr files onto it, then click "Generate keyframes" (after positioning and scaling it as needed); then the animation will play slowly capturing 24 fps.

After the frame captures occur, you can scroll through them and use a cropping tool to trim the canvas to the size of your animation. Once crop size is determined, just press "Crop and Generate" to export images.zip which will contain a folder with all the keyframes (24 fps) of the animation.

From here you can put them into photoshop or some software to make a GIF or you can use TexturePacker or the like to make a JSON atlas to use for animation. It's not a complete solution but might help someone out.

**Comment by sebasvil20** [comment]
> 
> 
> I've put together a tool that allows you to export keyframes in a zip from an export from rive.app. It's located at https://flare-sprite.herokuapp.com/ right now and uses the flare-js example as a jump off point.
> 
> You can drag and drop .flr files onto it, then click "Generate keyframes" (after positioning and scaling it as needed); then the animation will play slowly capturing 24 fps.
> 
> After the frame captures occur, you can scroll through them and use a cropping tool to trim the canvas to the size of your animation. Once crop size is determined, just press "Crop and Generate" to export images.zip which will contain a folder with all the keyframes (24 fps) of the animation.
> 
> From here you can put them into photoshop or some software to make a GIF or you can use TexturePacker or the like to make a JSON atlas to use for animation. It's not a complete solution but might help someone out.

That really help me, when it finish, the same page gives u the gif now, so you dont need to use more tools to do this. Just import the .flr files, adjust it, generate it, crop it and wait, it'll give u the .gif file too.

**Comment by IsaaacD** [comment]
Glad it helps! I've made a couple of updates to it as well so flr files with more than one animation can choose which one to use and FPS can be changed so you're not stuck with 24.

Also if the gif isn't loading allow pop up, it appears in a new tab.

**Comment by nmfisher** [comment]
@IsaaacD Seems your tool doesn't work with animated strokes? E.g. this one here:

https://rive.app/a/flschweiger/files/flare/phantom-handwriting

**Comment by IsaaacD** [comment]
@nmfisher I just use the Flare-JS library, so I'm not sure if it's related to the library (ie. not supported) or if there's some additional configuration I need to setup. I found this bug https://github.com/2d-inc/Flare-JS/issues/10 which isn't animated strokes but I think it might be the same idea as this is part of the changes in the bug fix was to add `component.markDirty();` :
```
case AnimatedPropertyTypes.FillOpacity:
case AnimatedPropertyTypes.StrokeOpacity:
	if (mix === 1.0) {
		component._Opacity = value;
	} else {
		component._Opacity = component._Opacity * imix + value * mix;
	}
	component.markDirty();
	break;
case AnimatedPropertyTypes.FillColor:
case AnimatedPropertyTypes.StrokeColor:
	{
		const color = component._Color;
		if (mix === 1.0) {
			color[0] = value[0];
			color[1] = value[1];
			color[2] = value[2];
			color[3] = value[3];
		} else {
			color[0] = color[0] * imix + value[0] * mix;
			color[1] = color[1] * imix + value[1] * mix;
			color[2] = color[2] * imix + value[2] * mix;
			color[3] = color[3] * imix + value[3] * mix;
		}
		component.markDirty();
		break;
	}
```
`component.markDirty();` called for `StrokeColor` and `StrokeOpacity` and was modified in the bug fix. So I've posted in the thread asking if there's anything else that needs to be setup as the example `.flr` the OP provided doesn't work in my tool either.

**Comment by Zaniyar** [comment]
Since the request was 2 years ago, I wanted to ask if there is any progress in this. Thank you.

**Comment by neurowave** [comment]
@Zaniyar we're currently working on our Cloud Renderer for the new version of Rive. You can track progress on our public roadmap/feature suggestion page here: https://feedback.rive.app/55

The old version of Rive (formerly Flare) will not be receiving new features.
