### ISSUE TITLE
making a ring of two ellipses with clip

### ISSUE THREAD

**Issue by jbshirk** [2d-inc/support#230]
I have two concentric ellipses 
1. larger: "inner diameter"
2. smaller: "rim web"

I am trying to subtract (mask) the smaller (the hole) from the larger to make it a ring.
for 1 I set clipping target to 2, but what happens is 1 becomes transparent and not 2. I have tried the reverse in case I misunderstood the usage, but it seems to have no effect.

I am at an impasse.

https://www.2dimensions.com/a/godparticle/files/flare/wheelchair-wheel

**Comment by neurowave** [comment]
We don't have a way to inverse clipping yet. In the meantime, you can achieve this by putting both paths on the same shape and setting the fill-rule property to even-odd. This is what is commonly used to create holes in vector letters like "o" or "e." https://docs.2dimensions.com/support/flare/vectors/fill#fill-rule

More info on the setting: https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule

Here's a GIF of what I did on your file to make it work:
![ellipse_ring](https://user-images.githubusercontent.com/1817068/59474984-f0573480-8dfd-11e9-9bd1-d454631cf314.gif)

- Drag the "rim web path" under the "rim web" shape to the "rim inner diameter" shape, so it's a sibling of "rim inner path."
- Select "rim inner diameter" shape and set its fill-rule to even-odd.

**Comment by neurowave** [comment]
By the way, you can delete the "rim web" shape after that. No need to keep it in the hierarchy.

**Comment by jbshirk** [comment]
Super! Thank you so much! I was pulling my hair out.
