### ISSUE TITLE
how to make child rotate on same axis as parent

### ISSUE THREAD

**Issue by jbshirk** [2d-inc/support#231]
I believe there is a way to do the following but I don't even know what to call it to search the docs for it.

I have a child node Stator1 located at the perimeter of its parent Wheel, a node. That is, its axis is offset from the parent's axis. I thought that as I rotate the parent, this child object would rotate with it on the same axis, but it's unaffected.

https://www.2dimensions.com/a/godparticle/files/flare/magic-wheel

**Comment by luigi-rosso** [comment]
You can re-parent the Stator node by dragging it into the Wheel on the hierarchy:
https://drive.google.com/file/d/1mQjHzSIOWNcvDKLWAhtW8RuCVWuNCxyK/view?usp=sharing

Does that look right?

**Comment by neurowave** [comment]
It looks like Wheel and Stator are siblings, not parent/child. To make Stator a child of Wheel, drag it under Wheel. Like this:
![2019-06-14 14 37 37](https://user-images.githubusercontent.com/1817068/59539419-09b9b880-8eb2-11e9-814c-aaf12bfb8868.gif)

**Comment by jbshirk** [comment]
No, Stator1 is a copy of Stator because I will be making 8 of them. So Stator is a sibling but Stator1 is a child.

**Comment by jbshirk** [comment]
the idea was to copy one into Wheel, rotate it 45 degrees, paste in another copy, and repeat until there are 8. and they should all rotate with Wheel.

**Comment by neurowave** [comment]
I see. Your Stator1 node is rotating with the wheel, it's just way off the screen. You can't see it. Select it and check the X and Y properties.

**Comment by jbshirk** [comment]
I see what part of the problem is. I was seeing Stator not move instead of Stator1. Making the prototype Stator hidden reveals that its copy, Stator1 isn't even visible. Looking at the drawing order, I see they are not where I expected them to land (and the parts are not grouped so they have to be multi-selected to move them together). But it seems no matter where I place them in the drawing order, they don't show.

**Comment by jbshirk** [comment]
I doublechecked Stator1's xy position. It's the same as its prototype, but I can't find it on the screen.

**Comment by jbshirk** [comment]
Now I am really confused. In Hierarchy view, Stator1's xy is correct, but in Drawing order, each component has a different position. I would have thought they would be the same as the parent node's xy. Are they relative to the Node?

**Comment by jbshirk** [comment]
I deleted the copy and started over with a new copy dragging it in as a child as shown. It worked. thanks!

**Comment by neurowave** [comment]
Just FYI, the X and Y values for position might look the same, but keep in mind those are local values. So if a parent at the root of the world is at 100,100 then its child at 0,0 is going to appear in the same location (its local value is 0,0 but its world location is 100,100 because of the parent). Whereas a child at 100,100 is actually going to be at 200,200 in world space.

That's why you couldn't see your Stator1 node. It was way off the screen. The position values looked the same, but because the parent had those same values, they were actually being doubled.

Hope that wasn't too confusing to follow…
