### ISSUE TITLE
 How can I get my project back to 20 hours ago?

### ISSUE THREAD

**Issue by KOOOOOOOP** [2d-inc/support#243]
I made some mistakes but I didn't have a backup,so how can I get my project back to 20 hours ago?     2dimensions Account email:sbmoonspirit@126.com     Username:KOP

**Comment by KOOOOOOOP** [comment]
this work: start_button

**Comment by neurowave** [comment]
You can see all your revisions under Settings > Revision History. Take a look at the manual here: https://docs.2dimensions.com/support/flare/revision-history
