### ISSUE TITLE
Rive doesn't export to JSON

### ISSUE THREAD

**Issue by mkabab** [2d-inc/support#258]
Hello all,
In Rive.app, I can't export my file to Json format, it's always exporting to flr file!

**Comment by tsinis** [comment]
> Hello all,
> In Rive.app, I can't export my file to Json format, it's always exporting to flr file!

It's correct, both exports will produce a FLR file, the only difference is, that JSON formatted FLR is human readable, so for example you can open it in any text editor and see all the values and keys there (formatted as JSON obviusly). Hope it helps!

**Comment by mkabab** [comment]
Thank you, it's working as you said.
