### ISSUE TITLE
How to report artist (obvious phishing)?

### ISSUE THREAD

**Issue by timohl** [2d-inc/support#262]
Hey, how can I report an artist that started following me?
The account is clearly only used for phishing (e.g. has malicious links in bio).
I cannot find any report option on the artists page.

**Comment by umberto-sonnino** [comment]
Could you send us an email at info@rive.app?
Thanks for reporting hits!

**Comment by timohl** [comment]
Done!

There should be an easier report option directly on the artists page though.

**Comment by antoniobologna** [comment]
I opened a similar issue a while back, but no response.
https://github.com/2d-inc/support/issues/267

**Comment by neurowave** [comment]
We blocked the account reported in this issue, just forgot to close it. Thanks for the reminder!

@antoniobologna Regarding your other issue, I sent you a response in the issue you linked, but here it is again:

We're working on a new Community for [Rive 2](https://beta.rive.app/) that will address this. In the meantime, please send reports to hello@rive.app.
