### ISSUE TITLE
[bug] Path gets broken when copy-paste (inside group)

### ISSUE THREAD

**Issue by braniii** [2d-inc/support#268]
I have a problem with your online editor. I created an athlete and my goal is to have two identical arms/legs. While it worked flawlessly to copy paste the arm, the path of the leg+pants get broken.

How to reproduce:

1. Open https://rive.app/a/braniii/files/flare/adonis/preview
2. Select Character->legs->legR group
3. copy paste
4. leg and pants will be gone.

**Comment by JcToon** [comment]
Hi Braniii,
I see the issue you're running into. What happens is that the shape of the leg and the pants are connected to the bone in the body. What you can do is disconnect the vertices and the bone of the body in the shape of the leg and pants. Then you duplicate in leg node legR group (check that now if you duplicate the leg and pants shape) and reconnect the vertices and the body bone.

This is a reference video.

I hope it helps you. 

Cheers.
[Leg_solution.mp4.zip](https://github.com/2d-inc/support/files/4541285/Leg_solution.mp4.zip)

**Comment by braniii** [comment]
Thank you so much for your help and the instructive video!
