### ISSUE TITLE
How to export animation in Rive 2?

### ISSUE THREAD

**Issue by rdmo94** [2d-inc/support#284]
I've tried to export the .riv file, but it's just showing the artboard in Flutter, and not the animation.
What am i doing wrong?

**Comment by TechnoLX** [comment]
i having same issue

**Comment by neurowave** [comment]
Hey @rdmo94 I think this probably belongs in https://github.com/rive-app/rive-flutter

Check that you're calling the right animation name. If you copy-pasted the code from one of our examples you may have forgotten to update the name of the animation. It needs to match the animation name in your file.

For example, from @mjohnsullivan's [examples repo](https://github.com/mjohnsullivan/rive-by-example), you'll see that he's calling an animation named "idle." This matches the animation name in the editor.

![Screen Shot 2021-02-06 at 1 32 30 PM](https://user-images.githubusercontent.com/1817068/107130187-f2e28980-687f-11eb-8f15-9caf12a549c7.png)
![Screen Shot 2021-02-06 at 1 34 31 PM](https://user-images.githubusercontent.com/1817068/107130200-13124880-6880-11eb-9a65-10191e4b2a09.png)
