### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by Cydo73** [2d-inc/support#289]
Hello, i made my splashscreen for my app last year using rive1 i think. I tried logging into the website to get my animation file's name, but that did not work
I tried logging into your website to create a new splashcreen using rive2, but the website freezes when i click "log in"
Why am i not logging in?

**Comment by umberto-sonnino** [comment]
If you're trying to login to Rive 1, you can do so with your credentials [here](https://flare.rive.app/signin). If those aren't working you can reset them [here](https://flare.rive.app/signin/forgot)
Rive 2 is a different product from Rive 1, so your old credentials don't work, but you can create a new account there too.

**Comment by Cydo73** [comment]
Oh..i just accessed it.
Thank you!
