### ISSUE TITLE
My SVG is not loaded 

### ISSUE THREAD

**Issue by serebroff** [2d-inc/support#291]
I got messages:
"Loading svg..."
"SVG loaded correctly..."
But it does not appear in the editor.

File attached:
[flight_sideview.svg.zip](https://github.com/2d-inc/support/files/6562889/flight_sideview.svg.zip)

**Comment by serebroff** [comment]
when I have used 'Export' in Illustrator instead 'Save as' - it began to work

**Comment by neurowave** [comment]
Check out our SVG importing tips. https://help.rive.app/editor/fundamentals/importing-assets

Also, this repository is for the old version of Rive (formerly Flare). To leave feedback for the new Rive, take a look at http://feedback.rive.app

For feedback on the new runtimes, you can find our new repositories at http://github.com/rive-app/
