### ISSUE TITLE
Incorrect hex value in color picker

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#36]
Compare Sketch color picker Hex value on right and Flare color picker on left. Looks like our hex values are being computed incorrectly.

![image 2018-10-26 at 4 18 59 pm](https://user-images.githubusercontent.com/1817068/47596410-067db680-d93b-11e8-935a-8a1cb6b94c21.png)

**Comment by luigi-rosso** [comment]
This should be fixed in build 1849.

**Comment by neurowave** [comment]
Fixed!
