### ISSUE TITLE
Convert Rounded Rectangle to Path

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#37]
Has unintended consequences. :) I think this is because the radius is too high in this case. We should probably still convert to how it was being rendered.

![screen recording 2018-10-26 at 04 34 pm](https://user-images.githubusercontent.com/1817068/47596728-21e9c100-d93d-11e8-9d9f-f8d218ad1040.gif)

**Comment by luigi-rosso** [comment]
This should be fixed in build 1849.

**Comment by neurowave** [comment]
Fixed!
