### ISSUE TITLE
Multiple shapes on shape layer don't render

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#38]
Multiple custom shapes on a shape layer don't display. Once you flatten them to a path (Convert to Path), then they render correctly.

Two shapes on one shape layer, one not being rendered:
![image 2018-10-26 at 4 40 45 pm](https://user-images.githubusercontent.com/1817068/47596852-37131f80-d93e-11e8-9dad-f83390ffdcc3.png)

Both shapes flattened into paths, now rendering correctly:
![image 2018-10-26 at 4 40 53 pm](https://user-images.githubusercontent.com/1817068/47596856-43977800-d93e-11e8-8014-add094fef2ec.png)

**Comment by luigi-rosso** [comment]
This should be fixed in build 1849.

**Comment by neurowave** [comment]
Confirmed fixed, closing!
