### ISSUE TITLE
Edit File Name on Public Page

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#41]
This one's also lower priority, but it would be nice to be able to rename your own files from the public page. Let you just click on it, like in Nima and Flare.

![image 2018-10-27 at 7 31 47 pm](https://user-images.githubusercontent.com/1817068/47611264-17075d00-da1f-11e8-9a66-152380c3a426.png)

**Comment by neurowave** [comment]
I fixed the styles for this. Ideally, we'd use the FileName.jsx component that we're using in Nima and Flare, so that the input field automatically resizes. @umberto-sonnino

**Comment by umberto-sonnino** [comment]
Alright thanks! 
I didn't use it as I thought you wanted to have a custom style for this page, but I can swap that in!

**Comment by neurowave** [comment]
Ah, makes sense! Maybe make a new component based on that one?
