### ISSUE TITLE
Key Interpolation window goes blank

### ISSUE THREAD

**Issue by justifun** [2d-inc/support#42]
I discovered that the key interpolation window with the "type" drop down and the curve adjusting area goes blank unless you refresh your scene

Steps to Reproduce

1: While in animate mode - switch back to setup mode
2: Parent an object under a node
3: switch back to animate mode and select a keyframe
Result:  key interpolation area is blank

workaround: refresh your webpage

expected: being able to adjust your key interpolation curves and types.

**Comment by luigi-rosso** [comment]
The issue occurred as we had a bug when registering selection events for keyframes after opening, closing, and re-opening the timeline. This should fix the various cases when interpolation options simply remained empty.

**Comment by luigi-rosso** [comment]
Will be fixed in build 1850.

**Comment by neurowave** [comment]
Awesome, thanks for catching and fixing this one. I was constantly running into it but hadn’t figured out that it was due to closing the timeline and re-opening it. I’ll test it out soon!

**Comment by neurowave** [comment]
Looks fixed on my end, I can't repro @justifun's steps anymore. I think we can close this if @justifun confirms!

**Comment by justifun** [comment]
Looks fixed from my end too !

**Comment by neurowave** [comment]
Closing!
