### ISSUE TITLE
Moving Bone After IK Target

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#59]
This was reported by JcToon.

> I have found a problem with the IK. When I move the bone that is after the IK, it seems that the IK setting is broken down. Then when I move the IK control, everything is put in place.

See attached video.

[Flare - Google Chrome 01_11_2018_Ik_problem_1.mp4.zip](https://github.com/2d-inc/support/files/2544558/Flare.-.Google.Chrome.01_11_2018_Ik_problem_1.mp4.zip)

**Comment by luigi-rosso** [comment]
So this actually exposes an interesting issue around using transformation tools on constrained bones. What I've done for now to solve it is basically prevent constrained nodes from being manipulated by a transformation that would break their constraints. This generally works well as it allows manipulating bones outside of the IK chain like so:

![constrained bones mov](https://user-images.githubusercontent.com/454182/48101884-68f97100-e1dd-11e8-8e23-761394e0063c.gif)

**Comment by neurowave** [comment]
Cool, makes sense. Closing!
