### ISSUE TITLE
Rounded Rectangles and Connected Bones

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#60]
Another one discovered by JcToon.

> Another problem I have found is connecting bones to the drone's camera. I made the camera a and a rectangle with rounded corners. the part of the lens is the same shape, but more adjusted. when I connect this shape to the bone, it changes the shape. Then I did it with an ellipse and it works well, so I think the problem is with the rectangle or the use of rounded corners.

See attached video:
[flare_-_google_chrome_01_11_conected_bones_problem_1.mp4.zip](https://github.com/2d-inc/support/files/2544560/flare_-_google_chrome_01_11_conected_bones_problem_1.mp4.zip)

**Comment by luigi-rosso** [comment]
I think this might've been related to the world transform issue JcToon caught. I cannot repro this with that fix in place, would be good to see if he can still repro it.
