### ISSUE TITLE
Show Keyboard Shortcuts in Flare/Nima

### ISSUE THREAD

**Issue by neurowave** [2d-inc/support#87]
@umberto-sonnino made a suggestion that we implement something similar to what Gmail does when you press Shift + ?

![image 2018-11-13 at 1 43 11 pm](https://user-images.githubusercontent.com/1817068/48444885-14f50c00-e74a-11e8-9c38-ca6b47f04468.png)

**Comment by jbshirk** [comment]
FYI, in Ubuntu/KDE + Firefox, CTRL + / does not activate keyboard shortcuts cheatsheet.
